AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  invoker-app

  Sample SAM Template for invoker-app

Parameters:
  Env:
    Type: String
    AllowedValues:
    - production
    - staging
    Default: staging
  SecurityGroupIds:
    Type: String
    Default: ''
  SubnetIds:
    Type: String
    Default: ''
  InvokeeEndpointUrl:
    Type: String
    Default: ''

Conditions:
  UseVpcConfig:
    Fn::And:
    - !Not [!Equals [!Ref SecurityGroupIds, '']]
    - !Not [!Equals [!Ref SubnetIds, '']]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  InvokerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub invoker-api-${Env}
      StageName: !Ref Env
      OpenApiVersion: 3.0.1

  InvokerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      VpcConfig:
        Fn::If:
        - UseVpcConfig
        - SecurityGroupIds: !Split [ ',', !Ref SecurityGroupIds ]
          SubnetIds: !Split [ ',', !Ref SubnetIds ]
        - !Ref AWS::NoValue
      Environment:
        Variables:
          INVOKEE_ENDPOINT_URL: !Ref InvokeeEndpointUrl
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref InvokerApi

Outputs:
  InvokerApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${InvokerApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/hello/"
  InvokerFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt InvokerFunction.Arn
  InvokerFunctionIamRole:
    Description: "Lambda Function IAM Role"
    Value: !GetAtt InvokerFunctionRole.Arn
